qa_crowbarsetup: use 9GB flavor
this is a partial revert of commit d52cd69c7

We found that a Hyper-V compute node would refuse
to start an 8GB image in an 8GB flavor
being off by 472 KB - possibly for some metadata

exact error message was:
HyperVException: Cannot resize the image to a size smaller than the VHD max. internal size: 8590417920. Requested disk size: 8589934592